kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgresql
  namespace: postgres
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi