apiVersion: v1
kind: Service
metadata:
  name: squid-service-NodeName0
  labels:
    app: squid-NodeName0
spec:
  type: NodePort
  ports:
    - port: 31280
      targetPort: 3128
      nodePort: 31280
  selector:
    app: squid-NodeName0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment-NodeName0
spec:
  selector:
    matchLabels:
      app: squid-NodeName0
  template:
    metadata:
      labels:
        app: squid-NodeName0
    spec:
      containers:
        - name: squid
          image: ubuntu/squid:5.2-22.04_beta
          ports:
            - containerPort: 3128
              name: squid
              protocol: TCP
          volumeMounts:
            - name: squid-config-volume
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
      volumes:
        - name: squid-config-volume
          configMap:
            name: squid-config
            items:
              - key: squid
                path: squid.conf
      nodeName: NodeName0
