apiVersion: v1
kind: Service
metadata:
  name: squid-service-0
  labels:
    app: squid-0
spec:
  type: NodePort
  ports:
    - port: 3128
      targetPort: 3128
      nodePort: 31280
  selector:
    app: squid-0
---
apiVersion: v1
kind: Service
metadata:
  name: squid-service-1
  labels:
    app: squid-1
spec:
  type: NodePort
  ports:
    - port: 3128
      targetPort: 3128
      nodePort: 31281
  selector:
    app: squid-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment-0
spec:
  selector:
    matchLabels:
      app: squid-0
  template:
    metadata:
      labels:
        app: squid-0
    spec:
      containers:
        - name: squid
          image: ubuntu/squid:edge
          ports:
            - containerPort: 3128
              name: squid
              protocol: TCP
          volumeMounts:
            - name: squid-config-volume
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
      volumes:
        - name: squid-config-volume
          configMap:
            name: squid-config
            items:
              - key: squid
                path: squid.conf
      nodeName: arm-node0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment-1
spec:
  selector:
    matchLabels:
      app: squid-1
  template:
    metadata:
      labels:
        app: squid-1
    spec:
      containers:
        - name: squid
          image: ubuntu/squid:edge
          ports:
            - containerPort: 3128
              name: squid
              protocol: TCP
          volumeMounts:
            - name: squid-config-volume
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf

      volumes:
        - name: squid-config-volume
          configMap:
            name: squid-config
            items:
              - key: squid
                path: squid.conf
      nodeName: arm-node1
