apiVersion: v1
kind: Service
metadata:
  name: squid-service
  labels:
    app: squid-service-app
spec:
  type: NodePort
  ports:
    - port: 3128
      targetPort: 3128
      nodePort: 31280
  selector:
    app: squid-proxy